version: "3.3"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.12.0"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    mem_limit: 1g
    networks:
      - kubevious
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"

networks:
  kubevious:
    external: true
